package com.example.slurm.controllers;

import com.example.slurm.models.Job;
import com.example.slurm.repositories.JobRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

import javax.servlet.http.HttpServletRequest;

@Controller
public class JobController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private JobRepository jobRepository;


    @GetMapping(path = "/job")
    public String getAllJobs(HttpServletRequest request, Model model) {
        int page = 0; //default page number is 0 (yes it is weird)
        int size = 12; //default page size is 10

        if (request.getParameter("page") != null && !request.getParameter("page").isEmpty()) {
            page = Integer.parseInt(request.getParameter("page")) - 1;
        }

        if (request.getParameter("size") != null && !request.getParameter("size").isEmpty()) {
            size = Integer.parseInt(request.getParameter("size"));
        }

        model.addAttribute("job", jobRepository.findAll(PageRequest.of(page, size)));
        return "job";
    }
    //public String getAllJobs(Model model) {
    //This returns a JSON or XML with the user
    //    model.addAttribute("job", jobRepository.findAll());
    //return jobRepository.findAll();
    //    return "job";
    //}

    //Job job = new Job();
}
