package com.example.slurm.controllers;

import com.example.slurm.models.Job;
import com.example.slurm.repositories.JobRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class JobController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private JobRepository jobRepository;

    @GetMapping(path = "/job")
    public String getAllJobs(Model model) {
        //This returns a JSON or XML with the user
        model.addAttribute("job", jobRepository.findAll());
        //return jobRepository.findAll();
        return "job";
    }

    Job job = new Job();
}
