package com.example.slurm.controllers;

import com.example.slurm.models.Job;
import com.example.slurm.repositories.JobRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class SlurmBDController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private JobRepository jobRepository;

    @GetMapping(path = "/statistics")
    public @ResponseBody
    Iterable<Job> getAllJobs() {
        //This returns a JSON or XML with the users
        return jobRepository.findAll();
    }

}
