package com.example.slurm.controllers;

import com.example.slurm.models.Statistics;
import com.example.slurm.repositories.StatisticsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

import java.math.BigDecimal;

@Controller
public class StatisticsController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StatisticsRepository statisticsRepository;


    public StatisticsRepository getStatisticsRepository() {
        return (StatisticsRepository) statisticsRepository.findAll();
    }

   /* @GetMapping(path = "/statistics")
   public String statistics(Model model){
        model.addAttribute("statistics", statisticsRepository.findAll());
        return "statistics";
    }
     */
    @GetMapping("/getsumtimestart")
    public Integer getsumtimestart(){
        Statistics stat = new Statistics();
        return statisticsRepository.selectTimeStart();
    }


}

