package com.example.slurm.controllers;

import com.example.slurm.models.Statistics;
import com.example.slurm.repositories.StatisticsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.concurrent.atomic.AtomicReference;

@Controller
public class StatisticsController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StatisticsRepository statisticsRepository;

    @GetMapping(path = "/statistics")
    public @ResponseBody
    AtomicReference<Integer> getAllJob() {
        //This returns a JSON or XML with the user
        Iterable<Statistics> stats = statisticsRepository.findAll();
        AtomicReference<Integer> sum = new AtomicReference<>(0);
        stats.forEach(s -> sum.updateAndGet(v -> v + s.count()));
        return sum;
    }
}

